### ISSUE TITLE
In Windows 10 dlisio.load will not release its file lock upon exception.

### ISSUE THREAD

**Issue by cimka** [equinor/dlisio#186]
Im using Python 3.6.8.
dlisio 0.1.14
Running on Windows 10.

In the workflow we have, we are downloading one dlis file at a time and remove them after we are done with them.

If we have a faulty dlis file that generate lets say this error:
- record-length in record 3 corrupted

Shortened code example:
```python
try:
    self.dlis = dlisio.load(self.file_name)
except Exception:
    os.remove(self.file_name)
```

When running this part of the code on a Linux system the file gets removed.
But when running on Windows 10 the os.remove will throw and exception ([Win Error 32] The process cannot access the file because it is being used by another process)

This issue only occurs if the file is corrupt/cannot be read. If file is read correctly we can remove it correctly after use in Linux and Windows.

**Comment by jokva** [comment]
Thanks for the report.

The reason it works on linux and fails on windows is probably that unlinking/deleting a file on linux while a handle is still open works fine, the actual deletion happens after the last-open file handle is closed (which is process teardown), whereas on windows the file is _locked_.

We have a pretty good idea on what's going on - it's a subtle race for an exception in load itself. I'd like to write a test case for it first which I suspect is a little bit difficult, but there you go.

**Comment by cimka** [comment]
> Thanks for the report.
> 
> The reason it works on linux and fails on windows is probably that unlinking/deleting a file on linux while a handle is still open works fine, the actual deletion happens after the last-open file handle is closed (which is process teardown), whereas on windows the file is _locked_.
> 
> We have a pretty good idea on what's going on - it's a subtle race for an exception in load itself. I'd like to write a test case for it first which I suspect is a little bit difficult, but there you go.

Thanks for response and I understand its not the most easy test case. 
For the moment it is not a critical thing for us but would be nice if it could be fixed. 
Kind regards Magnus

**Comment by ErlendHaa** [comment]
This got fixed by #237, which is part of the new release v0.1.16 [1]

[1] https://github.com/equinor/dlisio/blob/master/CHANGELOG.md

**Comment by cimka** [comment]
Have now verified that this works for me also. Great work! 👍

**Comment by SwordSam** [comment]
Hi This is still happening on version  0.2.3
Is there anything that I am missing?
Thanks

**Comment by achaikou** [comment]
Hi,

We believed that it wasn't a problem anymore, but we might have missed something. We have tests for checking whether file handles are closed for [correctly](https://github.com/equinor/dlisio/blob/0737750f5fb3787ab0a64b9f5e77ae3e81558537/python/tests/test_loading.py#L12) processed files and files which [failed on load](https://github.com/equinor/dlisio/blob/0737750f5fb3787ab0a64b9f5e77ae3e81558537/python/tests/test_loading.py#L45).

We might however have missed some setup, so it would be great to have the file for debugging.

**Comment by SwordSam** [comment]
Thanks, but sorry which file exactly?

**Comment by achaikou** [comment]
I assumed you see this behavior only for certain files - in this case it would be great to investigate the file itself.
Am I wrong? Does it happen for all the files? That would be weird. In that case could you please send the code snippet which causes the issue?

**Comment by SwordSam** [comment]
Hi,

Yes, it happens for all the files. 
The below code is part of the __init___ of a class:

 
          ` if self.extension == dlis:

            try:

                self.dlisfile_obj = dlisio.load(self.file_content)

            except Exception as ex:
                print(ex)

             then do series of action on the .dlis file`


and I call my class as below:

`

            with open('temp_file', 'wb') as temp_file:

                    temp_file.write(object_content)

                    myclass(file_content=temp_file.name)
`

So, object_content is content of a file I am reading from AWS S3 bucket and is a ByteIO type. I then write it to a temp_file (a simple temporary file- I know it is not the actual python temp file) and then pass it to __init__ of my class so dlisio.load() can read it and do some work with it.
The issue is after running the myclass() line I can't execute **os.remove('temp_file')** as it throws access denied error. 
Hope it makes sense,

I thought about using context manager, but that requires me to change of my code.
Happy to provide more details if needed :)
Thank you,

**Comment by achaikou** [comment]
It seems to me like you never close loaded file (at least I do not see it mentioned in your code). 
`self.dlisfile_obj = dlisio.load(self.file_content)`
Only closing file releases filehandles.

If you don't want to use "with" context manager, which closes files for you
```
with dlisio.load(self.file_content) as something:
    #do something
```

 you have to close the files batch explicitly

```
then do series of action on the .dlis file
self.dlisfile_obj.close()
```

(or one by one as in [this](https://github.com/equinor/dlisio/blob/0737750f5fb3787ab0a64b9f5e77ae3e81558537/python/tests/test_loading.py#L112) test)
